{{- $needsSecret := false }}
{{- $secretData := dict }}

{{- if not .Values.config.database.existingSecret }}
  {{- $needsSecret = true }}
  {{- $_ := set $secretData "db-password" (.Values.config.database.password | b64enc) }}
{{- end }}

{{- if not .Values.config.jwt.existingSecret }}
  {{- $needsSecret = true }}
  {{- $_ := set $secretData "jwt-secret" (.Values.config.jwt.secret | b64enc) }}
{{- end }}

{{- if and (eq .Values.config.cache.type "redis") (not .Values.config.cache.redis.existingSecret) }}
  {{- $needsSecret = true }}
  {{- $_ := set $secretData "redis-password" (.Values.config.cache.redis.password | b64enc) }}
{{- end }}

{{- if $needsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "togglr-backend.fullname" . }}-secret
  labels:
    {{- include "togglr-backend.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := $secretData }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}